# Generated by Django 5.0.4 on 2024-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_device_info_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
