# Generated by Django 5.0.4 on 2024-04-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='device_info',
        ),
    ]
